import SceneProvider from "@/context/scene/sceneProvider";
import ReactQueryProvider from "@/providers/ReactQueryProvider/ReactQueryProvider";
import ThemeProvider from "@/providers/ThemeProvider/ThemeProvider";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import React from "react";
import AuthLayout from "./authLayout";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html className="bg-black" lang="en">
      <body className="antialiased">
        <ReactQueryProvider>
          <ThemeProvider>
            <SessionProvider>
              <AuthLayout>
                <SceneProvider>
                  <main className="w-full h-full min-h-screen px-2 tablet:px-4 laptop:px-40 max-w-[1600px] mx-auto">
                    {children}
                  </main>
                </SceneProvider>
              </AuthLayout>
            </SessionProvider>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
