import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import AuthLayout from "./authLayout";
import "./globals.css";
import ThemeLayout from "./themeLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className="antialiased">
        <ThemeLayout>
          <SessionProvider>
            <AuthLayout>{children}</AuthLayout>
          </SessionProvider>
        </ThemeLayout>
      </body>
    </html>
  );
};

export default RootLayout;
